/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Usuário
 */
public class tela2 extends javax.swing.JFrame {

    /**
     * Creates new form tela2
     */
    public tela2() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(540, 363));
        setMinimumSize(new java.awt.Dimension(540, 363));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Clique no botão do icone desejado para executar");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(32, 33, 478, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jogovelha.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(76, 74, 162, 180);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(311, 260, 0, 0);

        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel7.setText("jogo da velha");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 280, 140, 23);

        jLabel8.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel8.setText("calculadora básica");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(300, 280, 200, 30);

        jLabel6.setBackground(new java.awt.Color(250, 250, 250));
        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 1, 17)); // NOI18N
        jLabel6.setText(" /");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(420, 210, 20, 20);

        jLabel10.setBackground(new java.awt.Color(250, 250, 250));
        jLabel10.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jLabel10.setText("  =");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(390, 210, 20, 20);

        jLabel11.setBackground(new java.awt.Color(250, 250, 250));
        jLabel11.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jLabel11.setText("  =");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(390, 210, 20, 20);

        jLabel12.setBackground(new java.awt.Color(250, 250, 250));
        jLabel12.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jLabel12.setText(".");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(350, 210, 20, 20);

        jLabel13.setBackground(new java.awt.Color(250, 250, 250));
        jLabel13.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jLabel13.setText("  =");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(390, 210, 20, 20);

        jLabel14.setBackground(new java.awt.Color(250, 250, 250));
        jLabel14.setFont(new java.awt.Font("Showcard Gothic", 1, 17)); // NOI18N
        jLabel14.setText(" -");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(420, 160, 20, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calculadora.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 70, 120, 180);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
