/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.loginmenu;

import br.edu.calculadora.Calculadora;
import br.edu.jogodavelha.JogoDaVelha;

/**
 *
 * @author Usuário
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form tela2
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        cliqueParaExecutar = new javax.swing.JLabel();
        jogoDaVelha = new javax.swing.JLabel();
        nomeJogodaVelha = new javax.swing.JLabel();
        nomeCalculadoraBasica = new javax.swing.JLabel();
        barraDividir = new javax.swing.JLabel();
        igual = new javax.swing.JLabel();
        pontoFlutuante = new javax.swing.JLabel();
        simMenos = new javax.swing.JLabel();
        calculadoraBasica = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(540, 363));
        setResizable(false);
        getContentPane().setLayout(null);

        cliqueParaExecutar.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        cliqueParaExecutar.setText("Clique no botão do ícone desejado para executar");
        getContentPane().add(cliqueParaExecutar);
        cliqueParaExecutar.setBounds(20, 23, 490, 30);

        jogoDaVelha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/imagens/jogovelha.png"))); // NOI18N
        jogoDaVelha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jogoDaVelhaMouseClicked(evt);
            }
        });
        getContentPane().add(jogoDaVelha);
        jogoDaVelha.setBounds(60, 80, 160, 160);

        nomeJogodaVelha.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        nomeJogodaVelha.setText("jogo da velha");
        getContentPane().add(nomeJogodaVelha);
        nomeJogodaVelha.setBounds(70, 270, 140, 30);

        nomeCalculadoraBasica.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        nomeCalculadoraBasica.setText("calculadora básica");
        getContentPane().add(nomeCalculadoraBasica);
        nomeCalculadoraBasica.setBounds(290, 270, 200, 30);

        barraDividir.setBackground(new java.awt.Color(250, 250, 250));
        barraDividir.setFont(new java.awt.Font("Showcard Gothic", 1, 17)); // NOI18N
        barraDividir.setText(" /");
        getContentPane().add(barraDividir);
        barraDividir.setBounds(410, 210, 20, 20);

        igual.setBackground(new java.awt.Color(250, 250, 250));
        igual.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        igual.setText("  =");
        getContentPane().add(igual);
        igual.setBounds(380, 210, 20, 20);

        pontoFlutuante.setBackground(new java.awt.Color(250, 250, 250));
        pontoFlutuante.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        pontoFlutuante.setText(".");
        getContentPane().add(pontoFlutuante);
        pontoFlutuante.setBounds(340, 210, 20, 20);

        simMenos.setBackground(new java.awt.Color(250, 250, 250));
        simMenos.setFont(new java.awt.Font("Showcard Gothic", 1, 17)); // NOI18N
        simMenos.setText(" -");
        getContentPane().add(simMenos);
        simMenos.setBounds(410, 160, 20, 20);

        calculadoraBasica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/imagens/calculadora.png"))); // NOI18N
        calculadoraBasica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calculadoraBasicaMouseClicked(evt);
            }
        });
        getContentPane().add(calculadoraBasica);
        calculadoraBasica.setBounds(320, 70, 120, 180);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jogoDaVelhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jogoDaVelhaMouseClicked

        dispose();
        JogoDaVelha jogo = new JogoDaVelha();
        jogo.inicio();
        jogo.setVisible(true);
    }//GEN-LAST:event_jogoDaVelhaMouseClicked

    private void calculadoraBasicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculadoraBasicaMouseClicked
        dispose();
        new Calculadora().setVisible(true);
    }//GEN-LAST:event_calculadoraBasicaMouseClicked

    /**
     * @param args the command line arguments
     */
/*    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela2().setVisible(true);
            }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barraDividir;
    private javax.swing.JLabel calculadoraBasica;
    private javax.swing.JLabel cliqueParaExecutar;
    private javax.swing.JLabel igual;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jogoDaVelha;
    private javax.swing.JLabel nomeCalculadoraBasica;
    private javax.swing.JLabel nomeJogodaVelha;
    private javax.swing.JLabel pontoFlutuante;
    private javax.swing.JLabel simMenos;
    // End of variables declaration//GEN-END:variables
}
